### PR TITLE
Feature/migrate to gradle

### PR DESCRIPTION
**Pull request by kotya341**
migration to gradle

### CODE REVIEW

**Comment by kotya341** [comment]
only one thing is weird why old files are not moved/removed.

**Comment by kotya341** [comment]
FYI when you migrate from old to gradle, android studio just add new file in the same directory without deleting old ones

**Comment by Tims101** [comment]
Thank you, @kotya341. Do you think we should store `import-summary.txt` in repo or it would be better to remove?

**Comment by kotya341** [comment]
@Tims101 np I'll delete it

**Comment by Tims101** [comment]
Awesome!

**Pull request merged**
